# Generated by Django 3.0.6 on 2020-05-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='short_note',
            field=models.TextField(max_length=100),
        ),
    ]
