# Generated by Django 3.0.6 on 2020-05-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200506_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='short_note',
            field=models.TextField(max_length=500),
        ),
    ]
