# Generated by Django 2.2.11 on 2020-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20200506_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='facebook',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='linkedIn',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='twitter',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
