# Generated by Django 3.0.6 on 2020-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200506_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='feature_image_1',
            field=models.ImageField(blank=True, default='/media/photos/default/default.jpg', upload_to='photos/property/%Y/%m/%d/'),
        ),
    ]
