# Generated by Django 3.0.6 on 2020-05-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200515_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='feature_image_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='feature_image_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='feature_image_5',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='feature_image_6',
        ),
    ]
