# Generated by Django 2.2.11 on 2020-05-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200520_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='Accra', max_length=50),
            preserve_default=False,
        ),
    ]
